<a href="https://colab.research.google.com/github/leeyerin25/TIL_python/blob/main/%EB%8D%B0%EC%B2%98%ED%94%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
bb = pd.read_csv('/content/drive/MyDrive/TEAM 11/gapminder.tsv', sep = '\t')

In [3]:
bb

country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

range 안에 모든걸 다 보여주려면 list 쓰기

In [4]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [5]:
list(range(0,6))

[0, 1, 2, 3, 4, 5]

In [6]:
bb.loc[ list(range(0,6,2))]

country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

In [7]:
bb.iloc[0:3 , list(range(0,6,2))]

country  year       pop
0  Afghanistan  1952   8425333
1  Afghanistan  1957   9240934
2  Afghanistan  1962  10267083

iloc 는 순번으로 뽑아줌 -> 0,2,4       6직전까지 뽑아줌

In [8]:
bb.iloc[0:3, 0:6:2] #0~6까지 두칸씩 띄기

country  year       pop
0  Afghanistan  1952   8425333
1  Afghanistan  1957   9240934
2  Afghanistan  1962  10267083

따옴표 안넣어도 되는경우 = 인덱스가 숫자로 되있을경우


loc 는 인덱스 번호를 뽑아줌 -> 0,2,4,6 추출이됨


In [9]:
bb.loc[0:6:2 , :]

country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
4  Afghanistan      Asia  1972   36.088  13079460  739.981106
6  Afghanistan      Asia  1982   39.854  12881816  978.011439

In [10]:
bb.iloc[0:3, 0:6:2]

country  year       pop
0  Afghanistan  1952   8425333
1  Afghanistan  1957   9240934
2  Afghanistan  1962  10267083

In [11]:
bb.iloc[0:3, list(range(0,6,2))]

country  year       pop
0  Afghanistan  1952   8425333
1  Afghanistan  1957   9240934
2  Afghanistan  1962  10267083

#오류확인

In [12]:
bb.iloc[0:3, 0:7:2]

country  year       pop
0  Afghanistan  1952   8425333
1  Afghanistan  1957   9240934
2  Afghanistan  1962  10267083

순번 6번이 없음 -> 관용성좋음

0~6 까지 인지하고 7은 없네하고 있는것만 표시

In [13]:
bb.iloc[0:3, list(range(0,7,2))]

IndexError: ignored

순번 6번이 없음 -> 아예 표시 안함

#NUMPY

##스칼라값

In [32]:
import numpy as np

In [33]:
aa = pd.Series(55)
aa

0    55
dtype: int64

In [34]:
type(aa)

pandas.core.series.Series

##문자

In [35]:
pd.Series('banana', index = [100])

100    banana
dtype: object

In [36]:
list_a = [1,2,3,4,7]

In [37]:
ex1 = pd.Series (data = list_a)
ex1

0    1
1    2
2    3
3    4
4    7
dtype: int64

In [38]:
type(ex1)

pandas.core.series.Series

In [39]:
ex1.dtypes

dtype('int64')

In [40]:
ex1.shape

(5,)

## 원소의 수

In [41]:
ex1.size

5

In [42]:
ex1.values #index 빼고 ndarray 만 불러주는 명령어

array([1, 2, 3, 4, 7])

In [43]:
type(ex1.values)

numpy.ndarray

index 정보 주는명령어   index = keys()

In [44]:
ex1.index

RangeIndex(start=0, stop=5, step=1)

In [45]:
ex1.keys()

RangeIndex(start=0, stop=5, step=1)

* 문제1) ex1 변수의 3번째 인덱스는?
* 문제2) ex1 변수의 3번째 데이터는?
* 문제3) 인덱스3에 해당하는 데이터는?

In [46]:
ex1.index[2] #0,1,2 3번쨰인덱스   or  ex1.keys()[2]

2

In [47]:
ex1[2] # ex1.values[2]   or  ex1.iloc[2]

3

In [48]:
ex1.loc[3]   # loc -> 인덱스기반임

4

In [49]:
ex1.loc[4]

7

가끔 pd 없이 series 쓰는경우 있는데..  pandas  series , dataframe 임폴트할겨우임

#9/28 ndarray 만들기

In [50]:
np.array( [4,3,5,8])

array([4, 3, 5, 8])

In [52]:
pd.Series(np.array( [4,3,5,8]))

0    4
1    3
2    5
3    8
dtype: int64

In [59]:
x = pd.Series(np.arange(10,60,10) , index=['a', 'b', 'c', 'd', 'e'])
x

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [60]:
x.loc[:'c']  #loc는 인덱스이용

a    10
b    20
c    30
dtype: int64

In [63]:
x.iloc[:3] 

a    10
b    20
c    30
dtype: int64

In [64]:
x.values[:3]  

array([10, 20, 30])

In [68]:
pd.Series ( {'a':4 , 'b':2 , 'c':3} )

a    4
b    2
c    3
dtype: int64

In [69]:
pd.Series ( {'a':4 , 'b':2 , 'c':3} ,                         
           index = ['b','c','a'])  #순서 재배열 시켜줌

b    2
c    3
a    4
dtype: int64

In [71]:
b = { 'a':4 , 'b':2 , 'c':3 }

In [72]:
y = pd.Series(b , index = ['b','c','a'])
y

b    2
c    3
a    4
dtype: int64

In [73]:
type(y)

pandas.core.series.Series

y 변수가 가진 index 만 뽑는법

In [75]:
y.keys()  # = y.index     

Index(['b', 'c', 'a'], dtype='object')

원소 수

In [76]:
y.size

3

In [81]:
y.keys()[2]  #   =  y.index[2]       

'a'

y변수의 index b 로 해당하는거 뽑기

In [82]:
y.loc['b']

2

시리즈는 열개념이 없음

In [83]:
y['b']     # 시리즈만 가능하고 데이터프레임에선 사용 불가능

2

In [93]:
Y = pd.Series( b, 
          index = ['b', 'c', 'a', 'e' ],  #  e 해당하는건 없다, 개수 맞추지않아도 나온다
          dtype=int , #dtype 넣어주면 해당하는걸로 바뀜. 
          name ='AAA' )  #여기서 주어진 이름이 데이터프레임에서 사용됨

Y   

b    2.0
c    3.0
a    4.0
e    NaN
Name: AAA, dtype: float64

In [95]:
Y.index.name = "OK"

Y  #인덱스 전체이름 OK , 데이터전체 NAME 은 AAA    *인덱스만 이름 지정 가능       쥐쥐~

OK
b    2.0
c    3.0
a    4.0
e    NaN
Name: AAA, dtype: float64

In [97]:
Y.name

'AAA'

#데이터프레임

행렬개념이 있는것. 인덱스와 컬럼 들어감       
* 1차원 리스트
 

In [99]:
h = [1,2,3,4] 
i = [4,3,2,1]
j = [5,6,7,8]
k = [8,7,6,5]

* 2차원 리스트

In [98]:
m = [[1,2,3,4] ,
[4,3,2,1],
[5,6,7,8],
[8,7,6,5]]

In [101]:
pd.DataFrame(m)

0  1  2  3
0  1  2  3  4
1  4  3  2  1
2  5  6  7  8
3  8  7  6  5

행이름 넣는법

In [105]:
p = { 'one' : [1,2,3,4] ,
'two' : [4,3,2,1],
'three' : [5,6,7,8],
'four':[8,7,6,5] }


In [107]:
pd.DataFrame(p)

one  two  three  four
0    1    4      5     8
1    2    3      6     7
2    3    2      7     6
3    4    1      8     5

열이름 넣는법

In [111]:
pd.DataFrame(p , index = ['1st' ,'2nd' ,'3rd','4th'])  #개오반데

one  two  three  four
1st    1    4      5     8
2nd    2    3      6     7
3rd    3    2      7     6
4th    4    1      8     5